from . import patients_data
from . import doctor_data 
from . import medicines
from . import lab_test
from . import appointment
from . import prescription_detail
from . import administrative_data
from . import bed_info
from . import patient_icu
from . import apache_score
from . import bed
from . import ecg
from . import pedriatic_symptoms
from . import newborn
from . import draft_lab_request
from . import test_cases
from . import nursing
from . import surgery_data
from . import medical_service
from . import invoice
from . import medicant_list
from . import laboratory_configuration
from . import configuration_disease
from . import health_center_configuration
from . import insurance_configuration
from . import medicament_configuration
from . import funvtion_model