from . import patients_data
from . import doctor_data 
from . import medicines
from . import lab_test
from . import appointment
from . import prescription_detail
from . import administrative_data
from . import bed_info
from . import patient_icu